#!/usr/bin/env bash
# Emulates a coding agent: writes a file and exits 0.
set -euo pipefail
mkdir -p src
printf '// generated by stub agent\n' > src/generated.txt
echo "stub agent wrote src/generated.txt"
